#!/bin/bash

mkdir build

cd build

git clone git@github.com:bstnfrmry/your-year-in-defocus.git --depth 1

cd your-year-in-defocus

cp ../../.env.production .

heroku container:push web -a your-year-in-slack

heroku container:release web -a your-year-in-slack

cd ../..

rm -rf build

heroku logs --tail -a your-year-in-slack
